"""
Patient browser page for CHARMTwinsights
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from api_client import (
    search_patients, get_patient_details, list_all_synthetic_patients,
    list_all_cohorts, get_cohort_metadata, delete_cohort,
    get_available_cohorts, get_visualization_image, load_resource_data
)
from utils import process_patient_search_results, process_synthetic_patients, process_cohorts_data


def show_patient_browser():
    """Patient data browser and analytics interface"""
    st.header("Patient Data Browser")
    st.markdown("Explore synthetic patient data with advanced analytics and visualizations")
    
    # Create tabs for different sections
    tab1, tab2, tab3, tab4, tab5 = st.tabs(["Patients", "Conditions", "Observations", "Procedures", "Cohorts"])
    
    with tab1:
        show_patients_section()
    
    with tab2:
        show_conditions_section()
    
    with tab3:
        show_observations_section()
    
    with tab4:
        show_procedures_section()
    
    with tab5:
        show_cohorts_section()


def show_patients_section():
    """Patient listing and search"""
    st.subheader("Patient Search & Listing")
    
    st.markdown("### FHIR Patient Search")
    
    # Search controls
    col1, col2, col3 = st.columns(3)
    
    with col1:
        search_name = st.text_input("Search by Name", placeholder="Enter patient name")
    
    with col2:
        search_gender = st.selectbox("Filter by Gender", ["All", "male", "female"])
    
    with col3:
        search_date = st.date_input("Birth Date", value=None)
    
    # Advanced search
    count_limit = st.slider("Number of Results", min_value=1, max_value=100, value=20)
    
    # Search button and results
    if st.button("Search FHIR Patients", type="primary"):
        birth_date_str = search_date.strftime("%Y-%m-%d") if search_date else None
        result = search_patients(search_name, search_gender, birth_date_str, count_limit)
        
        if result["success"]:
            data = result["data"]
            
            if data and "patients" in data and data["patients"]:
                patients_list = data["patients"]
                st.success(f"Found {len(patients_list)} patients")
                
                # Create patient table with proper field extraction
                df = process_patient_search_results(patients_list)
                st.dataframe(df, use_container_width=True)
                
                # Summary stats
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Total Found", len(patients_list))
                with col2:
                    gender_counts = df["Gender"].value_counts()
                    if len(gender_counts) > 0:
                        most_common = gender_counts.index[0]
                        st.metric("Most Common Gender", f"{most_common} ({gender_counts[most_common]})")
                with col3:
                    avg_age = df[df["Age"] != "N/A"]["Age"].astype(int).mean() if df[df["Age"] != "N/A"].shape[0] > 0 else "N/A"
                    if avg_age != "N/A":
                        st.metric("Average Age", f"{avg_age:.1f}")
                    else:
                        st.metric("Average Age", "N/A")
                
                # Patient details expansion
                if len(df) > 0:
                    selected_patient = st.selectbox("Select patient for details", 
                                                  [f"{row['ID']} - {row['Name']}" for _, row in df.iterrows()])
                    if selected_patient:
                        patient_id = selected_patient.split(" - ")[0]
                        show_patient_details(patient_id)
            else:
                st.info("No patients found with the specified criteria")
        else:
            st.error(f"Failed to search patients: {result['error']}")
    
    # Separate section for synthetic patients
    st.markdown("---")
    st.markdown("### Synthetic Patients Listing")
    st.info("View all synthetic patients generated by Synthea (includes cohort information)")
    
    if st.button("List All Synthetic Patients"):
        result = list_all_synthetic_patients()
        
        if result["success"]:
            data = result["data"]
            
            if data and "patients" in data and len(data["patients"]) > 0:
                patients_list = data["patients"]
                st.success(f"Found {len(patients_list)} synthetic patients")
                
                # Create patient table
                df, all_cohorts = process_synthetic_patients(patients_list)
                
                # Display table
                st.dataframe(df, use_container_width=True)
                
                # Summary metrics
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Total Patients", len(patients_list))
                with col2:
                    gender_counts = df["Gender"].value_counts()
                    if len(gender_counts) > 0:
                        most_common_gender = gender_counts.index[0]
                        st.metric("Most Common Gender", f"{most_common_gender} ({gender_counts[most_common_gender]})")
                with col3:
                    unique_cohorts = len(set(all_cohorts))
                    st.metric("Number of Cohorts", unique_cohorts)
                
            else:
                st.info("No synthetic patients found")
        else:
            st.error(f"Failed to fetch synthetic patients: {result['error']}")


def show_patient_details(patient_id):
    """Show detailed information for a specific patient"""
    st.subheader(f"Patient Details: {patient_id}")
    
    result = get_patient_details(patient_id)
    if result["success"]:
        st.json(result["data"])
    else:
        st.error(f"Failed to fetch patient details: {result['error']}")


def show_conditions_section():
    """Conditions analysis and visualization"""
    st.subheader("Conditions Analysis")
    
    # Controls
    col1, col2 = st.columns(2)
    with col1:
        limit = st.slider("Number of conditions to show", 5, 50, 20, key="conditions_limit")
    with col2:
        available_cohorts = get_available_cohorts()
        cohort_filter = st.selectbox("Filter by Cohort (optional)", 
                                   ["All"] + available_cohorts, 
                                   key="conditions_cohort")
        cohort_filter = cohort_filter if cohort_filter != "All" else None
    
    # Analysis tabs
    tab1, tab2, tab3, tab4 = st.tabs(["Overview", "By Gender", "By Age", "Data"])
    
    with tab1:
        st.markdown("**Most Common Conditions**")
        if st.button("Generate Conditions Visualization", key="viz_conditions"):
            show_visualization_image("/stats/visualize-conditions", limit, cohort_filter)
    
    with tab2:
        st.markdown("**Conditions by Gender**")
        if st.button("Generate Gender Breakdown", key="viz_conditions_gender"):
            show_visualization_image("/stats/visualize-conditions-by-gender", limit, cohort_filter)
    
    with tab3:
        st.markdown("**Conditions by Age Groups**")
        bracket_size = st.slider("Age bracket size (years)", 5, 20, 10, key="conditions_age_bracket")
        if st.button("Generate Age Breakdown", key="viz_conditions_age"):
            show_visualization_image("/stats/visualize-conditions-by-age", limit, cohort_filter, bracket_size)
    
    with tab4:
        if st.button("Load Conditions Data", key="load_conditions_data"):
            load_conditions_data()


def show_observations_section():
    """Observations analysis and visualization"""
    st.subheader("Observations Analysis")
    
    # Controls
    col1, col2 = st.columns(2)
    with col1:
        limit = st.slider("Number of observations to show", 5, 50, 20, key="observations_limit")
    with col2:
        available_cohorts = get_available_cohorts()
        cohort_filter = st.selectbox("Filter by Cohort (optional)", 
                                   ["All"] + available_cohorts, 
                                   key="observations_cohort")
        cohort_filter = cohort_filter if cohort_filter != "All" else None
    
    # Analysis tabs
    tab1, tab2, tab3, tab4 = st.tabs(["Overview", "By Gender", "By Age", "Data"])
    
    with tab1:
        st.markdown("**Most Common Observations**")
        if st.button("Generate Observations Visualization", key="viz_observations"):
            show_visualization_image("/stats/visualize-observations", limit, cohort_filter)
    
    with tab2:
        st.markdown("**Observations by Gender**")
        if st.button("Generate Gender Breakdown", key="viz_observations_gender"):
            show_visualization_image("/stats/visualize-observations-by-gender", limit, cohort_filter)
    
    with tab3:
        st.markdown("**Observations by Age Groups**")
        bracket_size = st.slider("Age bracket size (years)", 5, 20, 5, key="observations_age_bracket")
        if st.button("Generate Age Breakdown", key="viz_observations_age"):
            show_visualization_image("/stats/visualize-observations-by-age", limit, cohort_filter, bracket_size)
    
    with tab4:
        if st.button("Load Observations Data", key="load_observations_data"):
            load_observations_data()


def show_procedures_section():
    """Procedures analysis and visualization"""
    st.subheader("Procedures Analysis")
    
    # Controls
    col1, col2 = st.columns(2)
    with col1:
        limit = st.slider("Number of procedures to show", 5, 50, 20, key="procedures_limit")
    with col2:
        available_cohorts = get_available_cohorts()
        cohort_filter = st.selectbox("Filter by Cohort (optional)", 
                                   ["All"] + available_cohorts, 
                                   key="procedures_cohort")
        cohort_filter = cohort_filter if cohort_filter != "All" else None
    
    # Analysis tabs
    tab1, tab2, tab3, tab4 = st.tabs(["Overview", "By Gender", "By Age", "Data"])
    
    with tab1:
        st.markdown("**Most Common Procedures**")
        if st.button("Generate Procedures Visualization", key="viz_procedures"):
            show_visualization_image("/stats/visualize-procedures", limit, cohort_filter)
    
    with tab2:
        st.markdown("**Procedures by Gender**")
        if st.button("Generate Gender Breakdown", key="viz_procedures_gender"):
            show_visualization_image("/stats/visualize-procedures-by-gender", limit, cohort_filter)
    
    with tab3:
        st.markdown("**Procedures by Age Groups**")
        bracket_size = st.slider("Age bracket size (years)", 5, 20, 10, key="procedures_age_bracket")
        if st.button("Generate Age Breakdown", key="viz_procedures_age"):
            show_visualization_image("/stats/visualize-procedures-by-age", limit, cohort_filter, bracket_size)
    
    with tab4:
        if st.button("Load Procedures Data", key="load_procedures_data"):
            load_procedures_data()


def show_cohorts_section():
    """Cohort management and overview"""
    st.subheader("Cohort Management")
    
    # List all cohorts
    if st.button("List All Cohorts", key="list_cohorts"):
        result = list_all_cohorts()
        
        if result["success"]:
            data = result["data"]
            if data and "cohorts" in data:
                cohorts = data["cohorts"]
                total_cohorts = data.get("total_cohorts", len(cohorts))
                
                st.success(f"Found {total_cohorts} cohorts")
                
                # Create a nice table view
                df = process_cohorts_data(cohorts)
                st.dataframe(df, use_container_width=True)
                
                # Summary metrics
                col1, col2, col3 = st.columns(3)
                with col1:
                    total_patients = df["Patient Count"].sum()
                    st.metric("Total Patients", total_patients)
                with col2:
                    avg_size = total_patients / len(df) if len(df) > 0 else 0
                    st.metric("Avg Cohort Size", f"{avg_size:.1f}")
                with col3:
                    if len(df) > 0:
                        largest_idx = df["Patient Count"].idxmax()
                        largest_cohort = df.iloc[largest_idx]
                        st.metric("Largest Cohort", f"{largest_cohort['Cohort ID']} ({largest_cohort['Patient Count']})")
                
                # Show raw data if needed
                if st.checkbox("Show Raw JSON", key="show_raw_cohorts"):
                    with st.expander("Raw Response"):
                        st.json(data)
            else:
                st.info("No cohorts found")
        else:
            st.error(f"Failed to list cohorts: {result['error']}")
    
    st.markdown("---")
    
    # Cohort actions
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("**Cohort Information**")
        available_cohorts = get_available_cohorts()
        if available_cohorts:
            cohort_id_info = st.selectbox("Select cohort for metadata", 
                                        [""] + available_cohorts, 
                                        key="cohort_info_dropdown")
            if st.button("Get Cohort Metadata", key="get_cohort_meta") and cohort_id_info:
                result = get_cohort_metadata(cohort_id_info)
                if result["success"]:
                    st.json(result["data"])
                else:
                    st.error(f"Failed to get cohort metadata: {result['error']}")
        else:
            st.info("No cohorts available")
    
    with col2:
        st.markdown("**Cohort Management**")
        available_cohorts = get_available_cohorts()
        if available_cohorts:
            cohort_id_delete = st.selectbox("Select cohort to delete", 
                                          [""] + available_cohorts, 
                                          key="cohort_delete_dropdown")
            if cohort_id_delete:
                st.warning(f"⚠️ You are about to delete cohort: **{cohort_id_delete}**")
                confirm_delete = st.checkbox(f"I understand this action cannot be undone", key="confirm_delete")
                if st.button("🗑️ Delete Cohort", key="delete_cohort", type="secondary", disabled=not confirm_delete) and cohort_id_delete:
                    result = delete_cohort(cohort_id_delete)
                    if result["success"]:
                        st.success(f"Cohort deleted successfully: {result['data']}")
                        st.rerun()  # Refresh the page to update the dropdown
                    else:
                        st.error(f"Failed to delete cohort: {result['error']}")
        else:
            st.info("No cohorts available to delete")


def show_visualization_image(endpoint, limit, cohort_filter=None, bracket_size=None):
    """Display a visualization image from the stats API"""
    result = get_visualization_image(endpoint, limit, cohort_filter, bracket_size)
    
    if result["success"]:
        content_type = result["content_type"]
        
        if 'image' in content_type:
            # It's an image, display it directly
            st.image(result["content"], use_container_width=True)
        elif 'json' in content_type:
            # It's JSON, probably an error message
            try:
                import json
                error_data = json.loads(result["content"])
                st.error(f"Visualization failed: {error_data}")
            except:
                content_str = result["content"].decode('utf-8') if isinstance(result["content"], bytes) else str(result["content"])
                st.error(f"Visualization returned JSON instead of image: {content_str[:200]}...")
        else:
            # Unknown content type, show raw response for debugging
            st.error(f"Unexpected content type: {content_type}")
            with st.expander("Raw Response"):
                content_str = result["content"].decode('utf-8') if isinstance(result["content"], bytes) else str(result["content"])
                st.text(content_str[:500] + "..." if len(content_str) > 500 else content_str)
    else:
        st.error(f"Failed to generate visualization: {result['error']}")
        # Add debug info
        if st.sidebar.checkbox("Show Debug Info", key="debug_viz"):
            st.text(result["error"])


def load_conditions_data():
    """Load and display conditions data"""
    result = load_resource_data("conditions")
    if result["success"]:
        st.json(result["data"])
    else:
        st.error(f"Failed to load conditions data: {result['error']}")


def load_observations_data():
    """Load and display observations data"""
    result = load_resource_data("observations")
    if result["success"]:
        st.json(result["data"])
    else:
        st.error(f"Failed to load observations data: {result['error']}")


def load_procedures_data():
    """Load and display procedures data"""
    result = load_resource_data("procedures")
    if result["success"]:
        st.json(result["data"])
    else:
        st.error(f"Failed to load procedures data: {result['error']}")
